export const SET_ACCOUNTS = "SET_ACCOUNTS";

export const SET_ACTIVE_ACCOUNT = "SET_ACTIVE_ACCOUNT";

export const REFRESH_IDENTITY_REQUEST_PRICE = "REFRESH_IDENTITY_REQUEST_PRICE";

export const FETCH_MY_IDENTITY = "FETCH_MY_IDENTITY";

export const FETCH_MY_IDENTITY_PROVIDERS = "FETCH_MY_IDENTITY_PROVIDERS";

export const FETCH_IDENTITY_PROVIDERS = "FETCH_IDENTITY_PROVIDERS";
