export const SET_ACCOUNTS = "SET_ACCOUNTS";

export const SET_ACTIVE_ACCOUNT = "SET_ACTIVE_ACCOUNT";

export const REFRESH_IDENTITY_REQUEST_PRICE = "REFRESH_IDENTITY_REQUEST_PRICE";

export const FETCH_MY_IDENTITY = "FETCH_MY_IDENTITY";

export const FETCH_MY_IDENTITY_PROVIDERS = "FETCH_MY_IDENTITY_PROVIDERS";

export const FETCH_IDENTITY_PROVIDERS = "FETCH_IDENTITY_PROVIDERS";

export const RESET_IDENTITY_REQUEST_FORM_PROVIDER = "RESET_IDENTITY_REQUEST_FORM";

export const SET_IDENTITY_REQUEST_FORM_PROVIDER = "SET_IDENTITY_REQUEST_FORM_PROVIDER";

export const SET_IDENTITY_REQUEST_FORM_USERNAME = "SET_IDENTITY_REQUEST_FORM_USERNAME";

export const SET_IDENTITY_REQUEST_FORM_EVIDENCE = "SET_IDENTITY_REQUEST_FORM_EVIDENCE";

export const DO_IDENTITY_REQUEST = "DO_IDENTITY_REQUEST";

export const REFRESH_ETHER_PRICE = "REFRESH_ETHER_PRICE";