version: "3.7"
services:
  ipfs_host:
    image: ipfs/go-ipfs:v0.4.18
    volumes:
      - "/tmp/ipfs/staging:/export"
      - "/tmp/ipfs/data:/data/ipfs"
    ports:
      - "4001:4001"
      - "8080:8080"
      - "5001:5001"
    networks:
      ipfs:
        aliases:
          - ipfs_address

  ethereum-node:
    image: ethereum/client-go:v1.8.19
    volumes:
      - "/tmp/ethereum:/root"
    ports:
      - "8546:8546"
      - "30303:30303"
    networks:
      geth:
        aliases:
          - ethereum_address
    command: --rinkeby --ws --wsapi db,eth,net,web3,personal --wsaddr "0.0.0.0" --wsport 8546 --wsorigins="*" --syncmode=light

  indexer-service:
    image: bkent/permachat-indexer-service:v0.3
    depends_on:
      - "ethereum-node"
      - "ipfs_host"
    env_file:
      - docker.env
    networks:
      - ipfs
      - geth
    secrets:
      - PERMACHAT_INDEXER_ADMIN_PASSWORD
      - PERMACHAT_INDEXER_ADMIN_PRIVATEKEY

  identity-service:
    image: bkent/permachat-identity-service:v0.3.2
    depends_on:
      - "ethereum-node"
    env_file:
      - docker.env
    networks:
      - geth
    secrets:
      - PERMACHAT_IDENTITY_ADMIN_PRIVATEKEYHEX
      - PERMACHAT_IDENTITY_VALIDATORS_TWITTER_APIKEY
      - PERMACHAT_IDENTITY_VALIDATORS_TWITTER_APISECRETKEY

networks:
  geth:
  ipfs:

secrets:
  PERMACHAT_INDEXER_ADMIN_PASSWORD:
    file: "./secrets/PERMACHAT_INDEXER_ADMIN_PASSWORD"
  PERMACHAT_INDEXER_ADMIN_PRIVATEKEY:
    file: "./secrets/PERMACHAT_INDEXER_ADMIN_PRIVATEKEY"
  PERMACHAT_IDENTITY_ADMIN_PRIVATEKEYHEX:
    file: "./secrets/PERMACHAT_IDENTITY_ADMIN_PRIVATEKEYHEX"
  PERMACHAT_IDENTITY_VALIDATORS_TWITTER_APIKEY:
    file: "./secrets/PERMACHAT_IDENTITY_VALIDATORS_TWITTER_APIKEY"
  PERMACHAT_IDENTITY_VALIDATORS_TWITTER_APISECRETKEY:
    file: "./secrets/PERMACHAT_IDENTITY_VALIDATORS_TWITTER_APISECRETKEY"
